config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #reading convention
  get "/tasks", to: 'tasks#index'
  #creating convention
  get "/tasks/new", to: 'tasks#new'
  post "/tasks", to: 'tasks#create'
  get "/tasks/:id/edit", to: 'tasks#edit', as: :task_edit
  patch "tasks/:id", to: 'tasks#update'
  get "/tasks/:id", to: 'tasks#show', as: :task
  delete "/tasks/:id", to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.all
    end

    def show
        @task = Task.find(params[:id])
    end

    def new
        @task = Task.new()
    end

    def create
        @task = Task.new(task_params)
        @task.save
        redirect_to task_path(@task)
    end

    def edit
        @task = Task.find(params[:id])
    end

    def update
        @task = Task.update(task_params)
        redirect_to task_path(@task)
    end

    def destroy
        @task = Task.destroy(params[:id])
        redirect_to tasks_path
    end

    private

    def task_params
      params.require(:task).permit(:title, :details, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit a Task<%= @task.title %></h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class="container">
    <h1>All Tasks To Do</h1>
    <h3><%= link_to "To create a new task click click click", tasks_new_path%></h3>

    <%@tasks.each do |task|%>
    <ul>
    <li><%= link_to task.title, task_path(task)%></li>
    </ul>
    <% end %>
</div>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>Show the Task</h1>
<small>
  <%= link_to "Delete #{@task.title}",
              task_path(@task),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</small>

<ul>
<%=@task.title%>
<%=@task.details%>
</ul>
<%=link_to "Back to task list", tasks_path%>